
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComDevexpertsMobileDxplatformApiWatchlistIsInstrumentInFavoritesActionProvider")
#ifdef RESTRICT_ComDevexpertsMobileDxplatformApiWatchlistIsInstrumentInFavoritesActionProvider
#define INCLUDE_ALL_ComDevexpertsMobileDxplatformApiWatchlistIsInstrumentInFavoritesActionProvider 0
#else
#define INCLUDE_ALL_ComDevexpertsMobileDxplatformApiWatchlistIsInstrumentInFavoritesActionProvider 1
#endif
#undef RESTRICT_ComDevexpertsMobileDxplatformApiWatchlistIsInstrumentInFavoritesActionProvider

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (DXIsInstrumentInFavoritesActionProvider_) && (INCLUDE_ALL_ComDevexpertsMobileDxplatformApiWatchlistIsInstrumentInFavoritesActionProvider || defined(INCLUDE_DXIsInstrumentInFavoritesActionProvider))
#define DXIsInstrumentInFavoritesActionProvider_

#define RESTRICT_ComDevexpertsPipestoneCommonApiTypeProvider 1
#define INCLUDE_PSTypeProvider 1
#include "PSTypeProvider.h"

@interface DXIsInstrumentInFavoritesActionProvider : NSObject < PSTypeProvider >
@property (readonly, class, strong) DXIsInstrumentInFavoritesActionProvider *INSTANCE NS_SWIFT_NAME(INSTANCE);

+ (DXIsInstrumentInFavoritesActionProvider *)INSTANCE;

#pragma mark Public

- (instancetype __nonnull)init;

- (jint)getId;

@end

J2OBJC_STATIC_INIT(DXIsInstrumentInFavoritesActionProvider)

inline DXIsInstrumentInFavoritesActionProvider *DXIsInstrumentInFavoritesActionProvider_get_INSTANCE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT DXIsInstrumentInFavoritesActionProvider *DXIsInstrumentInFavoritesActionProvider_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(DXIsInstrumentInFavoritesActionProvider, INSTANCE, DXIsInstrumentInFavoritesActionProvider *)

FOUNDATION_EXPORT void DXIsInstrumentInFavoritesActionProvider_init(DXIsInstrumentInFavoritesActionProvider *self);

FOUNDATION_EXPORT DXIsInstrumentInFavoritesActionProvider *new_DXIsInstrumentInFavoritesActionProvider_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DXIsInstrumentInFavoritesActionProvider *create_DXIsInstrumentInFavoritesActionProvider_init(void);

J2OBJC_TYPE_LITERAL_HEADER(DXIsInstrumentInFavoritesActionProvider)

@compatibility_alias ComDevexpertsMobileDxplatformApiWatchlistIsInstrumentInFavoritesActionProvider DXIsInstrumentInFavoritesActionProvider;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComDevexpertsMobileDxplatformApiWatchlistIsInstrumentInFavoritesActionProvider")
