
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComDevexpertsDxmarketClientModelOrderBaseAttachPercentOfBalanceValueListener")
#ifdef RESTRICT_ComDevexpertsDxmarketClientModelOrderBaseAttachPercentOfBalanceValueListener
#define INCLUDE_ALL_ComDevexpertsDxmarketClientModelOrderBaseAttachPercentOfBalanceValueListener 0
#else
#define INCLUDE_ALL_ComDevexpertsDxmarketClientModelOrderBaseAttachPercentOfBalanceValueListener 1
#endif
#undef RESTRICT_ComDevexpertsDxmarketClientModelOrderBaseAttachPercentOfBalanceValueListener

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (DXMARKETAttachPercentOfBalanceValueListener_) && (INCLUDE_ALL_ComDevexpertsDxmarketClientModelOrderBaseAttachPercentOfBalanceValueListener || defined(INCLUDE_DXMARKETAttachPercentOfBalanceValueListener))
#define DXMARKETAttachPercentOfBalanceValueListener_

#define RESTRICT_ComDevexpertsDxmarketClientModelOrderBaseValueOrderEntryValueListener 1
#define INCLUDE_DXMARKETOrderEntryValueListener 1
#include "DXMARKETOrderEntryValueListener.h"

@class DXMARKETAttachedOrder;
@class DXMARKETValidationInfo;

@interface DXMARKETAttachPercentOfBalanceValueListener : NSObject < DXMARKETOrderEntryValueListener >

#pragma mark Public

- (instancetype __nonnull)initWithDXMARKETAttachedOrder:(DXMARKETAttachedOrder *)attachedOrder;

- (void)errorUpdatedWithDXMARKETValidationInfo:(DXMARKETValidationInfo *)newError;

- (void)valueUpdatedWithLong:(jlong)newValue;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(DXMARKETAttachPercentOfBalanceValueListener)

FOUNDATION_EXPORT void DXMARKETAttachPercentOfBalanceValueListener_initWithDXMARKETAttachedOrder_(DXMARKETAttachPercentOfBalanceValueListener *self, DXMARKETAttachedOrder *attachedOrder);

FOUNDATION_EXPORT DXMARKETAttachPercentOfBalanceValueListener *new_DXMARKETAttachPercentOfBalanceValueListener_initWithDXMARKETAttachedOrder_(DXMARKETAttachedOrder *attachedOrder) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DXMARKETAttachPercentOfBalanceValueListener *create_DXMARKETAttachPercentOfBalanceValueListener_initWithDXMARKETAttachedOrder_(DXMARKETAttachedOrder *attachedOrder);

J2OBJC_TYPE_LITERAL_HEADER(DXMARKETAttachPercentOfBalanceValueListener)

@compatibility_alias ComDevexpertsDxmarketClientModelOrderBaseAttachPercentOfBalanceValueListener DXMARKETAttachPercentOfBalanceValueListener;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComDevexpertsDxmarketClientModelOrderBaseAttachPercentOfBalanceValueListener")
