
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComDevexpertsDxmarketClientModelOrderOneclickBaseOneClickOrderTradingModel")
#ifdef RESTRICT_ComDevexpertsDxmarketClientModelOrderOneclickBaseOneClickOrderTradingModel
#define INCLUDE_ALL_ComDevexpertsDxmarketClientModelOrderOneclickBaseOneClickOrderTradingModel 0
#else
#define INCLUDE_ALL_ComDevexpertsDxmarketClientModelOrderOneclickBaseOneClickOrderTradingModel 1
#endif
#undef RESTRICT_ComDevexpertsDxmarketClientModelOrderOneclickBaseOneClickOrderTradingModel

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (DXMARKETBaseOneClickOrderTradingModel_) && (INCLUDE_ALL_ComDevexpertsDxmarketClientModelOrderOneclickBaseOneClickOrderTradingModel || defined(INCLUDE_DXMARKETBaseOneClickOrderTradingModel))
#define DXMARKETBaseOneClickOrderTradingModel_

#define RESTRICT_ComDevexpertsDxmarketClientModelOrderOneclickOneClickOrderTradingModel 1
#define INCLUDE_DXMARKETOneClickOrderTradingModel 1
#include "DXMARKETOneClickOrderTradingModel.h"

@protocol DXMARKETOneClickOrderTradingModel_Listener;
@protocol DXMARKETOneClickOrderTradingParams;

@interface DXMARKETBaseOneClickOrderTradingModel : NSObject < DXMARKETOneClickOrderTradingModel >

#pragma mark Public

- (instancetype __nonnull)initWithDXMARKETOneClickOrderTradingParams:(id<DXMARKETOneClickOrderTradingParams>)params;

- (void)addListenerWithDXMARKETOneClickOrderTradingModel_Listener:(id<DXMARKETOneClickOrderTradingModel_Listener> __nonnull)listener;

- (void)close;

- (void)issueOrderWithBoolean:(jboolean)isBuy;

- (void)removeListenerWithDXMARKETOneClickOrderTradingModel_Listener:(id<DXMARKETOneClickOrderTradingModel_Listener> __nonnull)listener;

- (void)updateQuantityWithNSString:(NSString * __nonnull)quantity;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(DXMARKETBaseOneClickOrderTradingModel)

FOUNDATION_EXPORT void DXMARKETBaseOneClickOrderTradingModel_initWithDXMARKETOneClickOrderTradingParams_(DXMARKETBaseOneClickOrderTradingModel *self, id<DXMARKETOneClickOrderTradingParams> params);

FOUNDATION_EXPORT DXMARKETBaseOneClickOrderTradingModel *new_DXMARKETBaseOneClickOrderTradingModel_initWithDXMARKETOneClickOrderTradingParams_(id<DXMARKETOneClickOrderTradingParams> params) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DXMARKETBaseOneClickOrderTradingModel *create_DXMARKETBaseOneClickOrderTradingModel_initWithDXMARKETOneClickOrderTradingParams_(id<DXMARKETOneClickOrderTradingParams> params);

J2OBJC_TYPE_LITERAL_HEADER(DXMARKETBaseOneClickOrderTradingModel)

@compatibility_alias ComDevexpertsDxmarketClientModelOrderOneclickBaseOneClickOrderTradingModel DXMARKETBaseOneClickOrderTradingModel;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComDevexpertsDxmarketClientModelOrderOneclickBaseOneClickOrderTradingModel")
